export const ORIENTATION_HORIZONTAL: number
export const ORIENTATION_VERTICAL: number
export const OVERFLOW_VISIBLE: number
export const OVERFLOW_HIDDEN: number
export const WRAP_WORD: number
export const WRAP_CHAR: number
export const WRAP_WORD_CHAR: number
export const ELLIPSIZE_NONE: number
export const ELLIPSIZE_START: number
export const ELLIPSIZE_MIDDLE: number
export const ELLIPSIZE_END: number
export const JUSTIFY_LEFT: number
export const JUSTIFY_RIGHT: number
export const JUSTIFY_CENTER: number
export const JUSTIFY_FILL: number
export const STYLE_PROVIDER_PRIORITY_FALLBACK: number
export const STYLE_PROVIDER_PRIORITY_THEME: number
export const STYLE_PROVIDER_PRIORITY_SETTINGS: number
export const STYLE_PROVIDER_PRIORITY_APPLICATION: number
export const STYLE_PROVIDER_PRIORITY_USER: number
export const PROPAGATION_PHASE_NONE: number
export const PROPAGATION_PHASE_CAPTURE: number
export const PROPAGATION_PHASE_BUBBLE: number
export const PROPAGATION_PHASE_TARGET: number
export const EVENT_SEQUENCE_STATE_NONE: number
export const EVENT_SEQUENCE_STATE_CLAIMED: number
export const EVENT_SEQUENCE_STATE_DENIED: number
export const INPUT_SOURCE_MOUSE: number
export const INPUT_SOURCE_PEN: number
export const INPUT_SOURCE_KEYBOARD: number
export const INPUT_SOURCE_TOUCHSCREEN: number
export const INPUT_SOURCE_TOUCHPAD: number
export const INPUT_SOURCE_TRACKPOINT: number
export const INPUT_SOURCE_TABLET_PAD: number
export const POLICY_ALWAYS: number
export const POLICY_AUTOMATIC: number
export const POLICY_NEVER: number
export const POLICY_EXTERNAL: number
export const SCROLL_MINIMUM: number
export const SCROLL_NATURAL: number
