const binding = require('../binding')

exports.ORIENTATION_HORIZONTAL = binding.ORIENTATION_HORIZONTAL
exports.ORIENTATION_VERTICAL = binding.ORIENTATION_VERTICAL

exports.OVERFLOW_VISIBLE = binding.OVERFLOW_VISIBLE
exports.OVERFLOW_HIDDEN = binding.OVERFLOW_HIDDEN

exports.WRAP_WORD = binding.WRAP_WORD
exports.WRAP_CHAR = binding.WRAP_CHAR
exports.WRAP_WORD_CHAR = binding.WRAP_WORD_CHAR

exports.ELLIPSIZE_NONE = binding.ELLIPSIZE_NONE
exports.ELLIPSIZE_START = binding.ELLIPSIZE_START
exports.ELLIPSIZE_MIDDLE = binding.ELLIPSIZE_MIDDLE
exports.ELLIPSIZE_END = binding.ELLIPSIZE_END
exports.JUSTIFY_LEFT = binding.JUSTIFY_LEFT
exports.JUSTIFY_RIGHT = binding.JUSTIFY_RIGHT
exports.JUSTIFY_CENTER = binding.JUSTIFY_CENTER
exports.JUSTIFY_FILL = binding.JUSTIFY_FILL

exports.STYLE_PROVIDER_PRIORITY_FALLBACK = binding.STYLE_PROVIDER_PRIORITY_FALLBACK
exports.STYLE_PROVIDER_PRIORITY_THEME = binding.STYLE_PROVIDER_PRIORITY_THEME
exports.STYLE_PROVIDER_PRIORITY_SETTINGS = binding.STYLE_PROVIDER_PRIORITY_SETTINGS
exports.STYLE_PROVIDER_PRIORITY_APPLICATION = binding.STYLE_PROVIDER_PRIORITY_APPLICATION
exports.STYLE_PROVIDER_PRIORITY_USER = binding.STYLE_PROVIDER_PRIORITY_USER

exports.PROPAGATION_PHASE_NONE = binding.PROPAGATION_PHASE_NONE
exports.PROPAGATION_PHASE_CAPTURE = binding.PROPAGATION_PHASE_CAPTURE
exports.PROPAGATION_PHASE_BUBBLE = binding.PROPAGATION_PHASE_BUBBLE
exports.PROPAGATION_PHASE_TARGET = binding.PROPAGATION_PHASE_TARGET

exports.EVENT_SEQUENCE_STATE_NONE = binding.EVENT_SEQUENCE_STATE_NONE
exports.EVENT_SEQUENCE_STATE_CLAIMED = binding.EVENT_SEQUENCE_STATE_CLAIMED
exports.EVENT_SEQUENCE_STATE_DENIED = binding.EVENT_SEQUENCE_STATE_DENIED

exports.INPUT_SOURCE_MOUSE = binding.INPUT_SOURCE_MOUSE
exports.INPUT_SOURCE_PEN = binding.INPUT_SOURCE_PEN
exports.INPUT_SOURCE_KEYBOARD = binding.INPUT_SOURCE_KEYBOARD
exports.INPUT_SOURCE_TOUCHSCREEN = binding.INPUT_SOURCE_TOUCHSCREEN
exports.INPUT_SOURCE_TOUCHPAD = binding.INPUT_SOURCE_TOUCHPAD
exports.INPUT_SOURCE_TRACKPOINT = binding.INPUT_SOURCE_TRACKPOINT
exports.INPUT_SOURCE_TABLET_PAD = binding.INPUT_SOURCE_TABLET_PAD

exports.POLICY_ALWAYS = binding.POLICY_ALWAYS
exports.POLICY_AUTOMATIC = binding.POLICY_AUTOMATIC
exports.POLICY_NEVER = binding.POLICY_NEVER
exports.POLICY_EXTERNAL = binding.POLICY_EXTERNAL

exports.SCROLL_MINIMUM = binding.SCROLL_MINIMUM
exports.SCROLL_NATURAL = binding.SCROLL_NATURAL
