const binding = require('../binding')

exports.ORIENTATION_HORIZONTAL = binding.ORIENTATION_HORIZONTAL
exports.ORIENTATION_VERTICAL = binding.ORIENTATION_VERTICAL

exports.OVERFLOW_VISIBLE = binding.OVERFLOW_VISIBLE
exports.OVERFLOW_HIDDEN = binding.OVERFLOW_HIDDEN

exports.WRAP_WORD = binding.WRAP_WORD
exports.WRAP_CHAR = binding.WRAP_CHAR
exports.WRAP_WORD_CHAR = binding.WRAP_WORD_CHAR

exports.JUSTIFY_LEFT = binding.JUSTIFY_LEFT
exports.JUSTIFY_RIGHT = binding.JUSTIFY_RIGHT
exports.JUSTIFY_CENTER = binding.JUSTIFY_CENTER
exports.JUSTIFY_FILL = binding.JUSTIFY_FILL

exports.STYLE_PROVIDER_PRIORITY_FALLBACK = binding.STYLE_PROVIDER_PRIORITY_FALLBACK
exports.STYLE_PROVIDER_PRIORITY_THEME = binding.STYLE_PROVIDER_PRIORITY_THEME
exports.STYLE_PROVIDER_PRIORITY_SETTINGS = binding.STYLE_PROVIDER_PRIORITY_SETTINGS
exports.STYLE_PROVIDER_PRIORITY_APPLICATION = binding.STYLE_PROVIDER_PRIORITY_APPLICATION
exports.STYLE_PROVIDER_PRIORITY_USER = binding.STYLE_PROVIDER_PRIORITY_USER
